<?php

require_once 'PHPUnit/Autoload.php';

require_once dirname(__FILE__) . '/../String.php';
require_once dirname(__FILE__) . '/../StringException.php';

/**
 * Test class for StringException.
 * Generated by PHPUnit on 2011-11-19 at 18:31:45.
 */
class StringExceptionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var StringException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new StringException();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * @expectedException StringException
   */
  public function testException() {
    new String(5);
  }

}